<div class="container">
    <nav class="menu navbar navbar-expand-lg navbar-dark bg-dark">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="index.php">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="amanda.php">Amanda</a></li>
            <li class="nav-item"><a class="nav-link" href="jacob.php">Jacob</a></li>
            <li class="nav-item"><a class="nav-link" href="joseph.php">Joseph</a></li>
        </ul>

    </nav>
</div>